services:
  postgres:
    container_name: postgres
    image: postgres:17.2-bookworm
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./r18-db:/var/lib/postgresql/data
      - ./setup_db.sh:/setup_db.sh
